// Render the folded tracker into the canonical `{tracker,epics,state}.ttl` trio.
//
// BYTE-FAITHFUL PORT of the render* functions in
// codespaces/src/lib/tracker/build.ts. Every concat order, the
// `replace(/ ;\n$/, " .\n")` close-statement trick, the per-file prefix lists,
// and the base IRIs must match exactly or the golden diff against that repo's
// committed build/*.ttl will fail. Do not "tidy" this — keep it identical.

const NS = {
  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
  flow: "http://www.w3.org/2005/01/wf/flow#",
  wf: "http://www.w3.org/2005/01/wf/flow#",
  dct: "http://purl.org/dc/terms/",
  dc: "http://purl.org/dc/elements/1.1/",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  ui: "http://www.w3.org/ns/ui#",
  owl: "http://www.w3.org/2002/07/owl#",
  foaf: "http://xmlns.com/foaf/0.1/",
};

function className(id) {
  return String(id)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

function ttlLong(text) {
  let s = text.replace(/\\/g, "\\\\");
  s = s.replace(/"""/g, '\\"\\"\\"');
  if (s.endsWith('"')) s = s.slice(0, -1) + '\\"';
  return `"""${s}"""`;
}

function ttlShort(text) {
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function prefixHeader(prefixes, base) {
  return `@prefix : <${base}> .\n` + prefixes.map((p) => `@prefix ${p}: <${NS[p]}> .\n`).join("");
}

function issueFrag(id) {
  return id;
}

export function renderTracker(cfg) {
  let out = prefixHeader(["rdfs", "flow", "dct", "xsd", "ui", "owl", "foaf"], "#");
  out += `@prefix mc: <${cfg.namespace}> .\n\n`;
  out += `# Generated by scripts/tracker-build.ts from .mind/issues/tracker.config.md — do not edit by hand.\n`;
  out += `# Conforms to the Solid IssueTrackerShape (https://github.com/solid/shapes).\n\n`;

  out += `#### Issue states (subClassOf flow:Open / flow:Closed) ####\n`;
  for (const s of cfg.states) {
    const c = className(s.id);
    const parent = s.open ? "flow:Open" : "flow:Closed";
    out += `:${c} a rdfs:Class ;\n`;
    out += `    rdfs:label ${ttlShort(s.label)} ;\n`;
    out += `    rdfs:subClassOf ${parent} , :Issue ;\n`;
    if (s.sortOrder != null) out += `    ui:sortOrder ${s.sortOrder} ;\n`;
    if (s.color) out += `    ui:backgroundColor ${ttlShort(s.color)} ;\n`;
    out = out.replace(/ ;\n$/, " .\n") + "\n";
  }

  out += `#### Issue class (flow:issueClass) ####\n`;
  out += `:Issue a rdfs:Class ;\n`;
  out += `    rdfs:label "Issue" ;\n`;
  out += `    rdfs:subClassOf flow:Task ;\n`;
  out += `    owl:disjointUnionOf ( ${cfg.states.map((s) => ":" + className(s.id)).join(" ")} ) .\n\n`;

  out += `#### Issue categories (flow:issueCategory) ####\n`;
  for (const c of cfg.categories) {
    out += `:${className(c.id)} a rdfs:Class ;\n`;
    out += `    rdfs:label ${ttlShort(c.label)} ;\n`;
    out += `    rdfs:subClassOf :Category ;\n`;
    if (c.color) out += `    ui:backgroundColor ${ttlShort(c.color)} ;\n`;
    out = out.replace(/ ;\n$/, " .\n") + "\n";
  }
  out += `:Category a rdfs:Class ;\n`;
  out += `    rdfs:label "category" ;\n`;
  out += `    owl:disjointUnionOf ( ${cfg.categories.map((c) => ":" + className(c.id)).join(" ")} ) .\n\n`;

  out += `#### The tracker ####\n`;
  out += `:this a flow:Tracker ;\n`;
  out += `    dct:title ${ttlShort(cfg.title)} ;\n`;
  out += `    rdfs:label ${ttlShort(cfg.title)} ;\n`;
  if (cfg.description) out += `    flow:description ${ttlShort(cfg.description)} ;\n`;
  out += `    flow:issueClass :Issue ;\n`;
  out += `    flow:issueCategory :Category ;\n`;
  out += `    flow:initialState :${className(cfg.initialState)} ;\n`;
  out += `    flow:defaultView flow:${cfg.defaultView} ;\n`;
  out += `    flow:assigneeClass ${cfg.assigneeClass} ;\n`;
  out += `    flow:allowSubIssues ${cfg.allowSubIssues ? "true" : "false"} ;\n`;
  if (cfg.properties.length)
    out += `    flow:propertyList ( ${cfg.properties.map((p) => "mc:" + p).join(" ")} ) ;\n`;
  out += `    flow:stateStore <state.ttl> .\n`;
  return out;
}

export function renderEpics(cfg, epics) {
  let out = prefixHeader(["rdfs", "dct", "xsd"], "#");
  out += `@prefix mc: <${cfg.namespace}> .\n\n`;
  out += `# Generated by scripts/tracker-build.ts from .mind/issues/*/epic.md — do not edit by hand.\n`;
  out += `# Each mc:Epic is a goal grouping a collection of issues (see state.ttl mc:epic links).\n\n`;
  for (const e of epics) {
    if (e.isGeneral) continue;
    const lines = [];
    lines.push(`a mc:Epic`);
    lines.push(`mc:number ${e.number}`);
    lines.push(`dct:title ${ttlShort(e.title)}`);
    lines.push(`rdfs:label ${ttlShort(e.title)}`);
    lines.push(`mc:status ${ttlShort(e.status)}`);
    lines.push(`mc:issueCount ${e.issues.length}`);
    if (e.created) lines.push(`dct:created "${e.created}"^^xsd:date`);
    lines.push(`dct:description ${ttlLong(e.body)}`);
    out += `<#${e.slug}>\n    ` + lines.join(" ;\n    ") + " .\n\n";
  }
  return out;
}

export function renderState(cfg, epics) {
  let out = prefixHeader(["wf", "dct", "dc", "rdfs", "xsd", "foaf"], "tracker.ttl#");
  out += `@prefix mc: <${cfg.namespace}> .\n\n`;
  out += `# Generated by scripts/tracker-build.ts from .mind/issues/ (folded events/) — do not edit by hand.\n`;
  out += `# The tracker's flow:stateStore. An issue's state & category are its rdf:type;\n`;
  out += `# mc:epic links each issue to its epic in epics.ttl.\n\n`;

  for (const e of epics) {
    out += `#### ${e.isGeneral ? "General (un-epic'd)" : `Epic: ${e.slug}`} ####\n`;
    for (const i of e.issues) {
      const lines = [];
      lines.push(`wf:tracker :this`);
      if (i.number != null) lines.push(`mc:number ${i.number}`);
      if (!e.isGeneral) lines.push(`mc:epic <epics.ttl#${e.slug}>`);
      lines.push(`dc:title ${ttlShort(i.title)}`);
      lines.push(`a :${className(i.state)} , :${className(i.category)}`);
      if (i.created) lines.push(`dct:created "${i.created}"^^xsd:date`);
      if (i.modified) lines.push(`dct:modified "${i.modified}"^^xsd:date`);
      if (i.assignee) lines.push(`wf:assignee <${i.assignee}>`);
      if (i.afk != null) lines.push(`mc:afk ${i.afk ? "true" : "false"}`);
      if (i.blocks.length) lines.push(`mc:blocks ${i.blocks.map((b) => `<#${issueFrag(b)}>`).join(" , ")}`);
      if (i.blockedBy.length)
        lines.push(`mc:blockedBy ${i.blockedBy.map((b) => `<#${issueFrag(b)}>`).join(" , ")}`);
      lines.push(`wf:description ${ttlLong(i.body)}`);
      out += `<#${issueFrag(i.id)}>\n    ` + lines.join(" ;\n    ") + " .\n\n";
    }
  }
  return out;
}

export { className };
