// `mind issues init` — lay down a fresh `.mind/` issue tracker skeleton:
// README.md + AGENTS.md (the human + machine contracts), issues/tracker.config.md
// (the authoritative vocab), a .gitignore for the generated build/, and the
// 00_general_issues/ lane. The default vocab matches the codespaces tracker so a
// freshly-init'd tracker folds with the same states/categories/axes.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { slugify } from "./author.mjs";

function trackerConfig(title, namespace) {
  return `---
title: ${JSON.stringify(title)}
description: "Epic-scoped, event-sourced. Issues are markdown folders with an append-only events/ log; \`mind issues build\` folds events to build/*.ttl. This frontmatter is the authoritative vocab."
namespace: ${JSON.stringify(namespace)}
initialState: needs-triage
# Current state is the FOLD of an issue's events/ — never a field on issue.md.
# These are the legal \`state:\` values an event may transition \`to:\`.
states:
  - id: needs-triage
    label: "needs triage"
    open: true
    handoff: human
  - id: ready-for-agent
    label: "ready for agent"
    open: true
    handoff: agent
  - id: ready-for-human
    label: "ready for human"
    open: true
    handoff: human
  - id: in-progress
    label: "in progress"
    open: true
  - id: blocked
    label: "blocked"
    open: true
  - id: done
    label: "done"
    open: false
  - id: wontfix
    label: "won't fix"
    open: false
# Issue categories (the \`type:\` axis).
categories:
  - id: feature
  - id: bug
  - id: refactor
  - id: chore
  - id: docs
# The four orthogonal axes a triager sets.
axes:
  type: categories
  state: states
  priority: [urgent, high, normal, low]
  labels: open-set
# Coordination for multi-agent work (claim before working).
coordination:
  claimTtl: PT2H
  tieBreak: lowest-ulid
  queueGateLabels: [human-only, needs-design, blocked]
# Generated — never hand-edit.
generated:
  - build/tracker.ttl
  - build/epics.ttl
  - build/state.ttl
---

# ${title}

This file's **YAML frontmatter is the source of truth** for the controlled vocabulary
(states, categories, axes, coordination). \`mind issues build\` reads it, folds every
issue's \`events/\` log to a current state, and writes \`build/{tracker,epics,state}.ttl\`.

- **State** is derived, not declared — it is the \`to:\` of an issue's latest state-changing event.
- **Categories** = the \`type:\` axis. **Priority/labels** are the other two triage axes.

Never hand-edit \`build/*\` — it is generated.
`;
}

const README = `# \`.mind\` — a Markdown, event-sourced issue tracker

An issue tracker that lives in the repo as plain files, built for **humans and agents to share
one source of truth**. Issues are folders, history is an append-only event log, and the current
state of everything is *derived* — never hand-set.

> **The path carries immutable context. The \`events/\` log carries state.**

A folder name only ever encodes facts that never change — the epic, the date it was filed.
Everything that *moves* — open → in-progress → done, who claimed it, priority, labels — lives in
the issue's \`events/\` log. Current state is the **fold** of that log.

## Layout

\`\`\`
.mind/
  README.md                         this file
  AGENTS.md                         the machine contract (append events; query, don't slurp)
  issues/
    tracker.config.md               states, categories, axes — AUTHORITATIVE vocab
    00_general_issues/              un-epic'd issues
      <ts>_<rand4>/                 ONE issue = a folder
        issue.md                    frontmatter (immutable facts) + body. NO state field.
        events/
          <date>-<hhmm>-<actor>-<kind>.md   append-only. The fold of these IS the state.
    <ts>_<rand4>/                   an EPIC — a goal + its issues
      epic.md                       the epic brief (id, title, status)
      <ts>_<rand4>/                 issue folders sit directly under the epic
        issue.md
        events/
  build/                            GENERATED by \`mind issues build\` — never hand-edit
    tracker.ttl  epics.ttl  state.ttl
\`\`\`

## Drive it with the mind CLI

\`\`\`bash
mind issues new "Fix the thing" --type bug --priority high
mind issues list
mind issues show MC-1
mind issues triage MC-1 --to ready-for-agent --labels area:io
mind issues claim MC-1
mind issues close MC-1 --to done
\`\`\`
`;

const AGENTS = `# AGENTS.md — machine contract for \`.mind\`

This tracker is read and written by agents. These rules are binding.

## Reading — query, never slurp

- **Facts** come from \`issue.md\` frontmatter; **narrative** from its body; **state & history**
  from \`events/\`.
- **Current state is the fold of \`events/\`** — the \`to:\` of the latest state-changing event.
  There is no \`state:\` field on the issue; do not invent one.

## Writing — events are the only way to change state

- **Change state = append one event** (\`mind issues triage|claim|state|handoff|close …\`).
  Do not edit \`issue.md\`'s body to record state.
- **Claim before working** (\`mind issues claim <ref>\`). Claims carry a ttl; lowest ULID wins ties.
- **Suggest, don't decide. Never self-close** — hand back with \`mind issues handoff\` to
  \`ready-for-human\`.
- **Respect gates.** Do not pick up issues labelled \`human-only\`, \`needs-design\`, or \`blocked\`.

## Event kinds

\`open\` · \`triage\` · \`claim\` · \`release\` · \`state\` · \`link\` · \`comment\` · \`handoff\` · \`close\`.

## Referencing issues

Reference an issue by its canonical **ULID** (\`issue.md\` \`id:\`), never by path or display handle.
`;

/**
 * Scaffold a `.mind/` tracker into `targetRoot`. Throws if one already exists
 * unless `force`. Returns the created paths.
 */
export function initTracker(targetRoot, { title, namespace, force = false } = {}) {
  const mind = join(targetRoot, ".mind");
  const issues = join(mind, "issues");
  const configFile = join(issues, "tracker.config.md");

  if (existsSync(configFile) && !force)
    throw new Error(`a .mind tracker already exists at ${mind} (pass --force to overwrite its config + docs)`);

  const resolvedTitle = title || `${basename(targetRoot)} tracker`;
  const slug = slugify(resolvedTitle) || "mind";
  const resolvedNs = namespace || `https://mindpods.org/ns/${slug}#`;

  mkdirSync(join(issues, "00_general_issues"), { recursive: true });
  writeFileSync(join(mind, "README.md"), README, "utf8");
  writeFileSync(join(mind, "AGENTS.md"), AGENTS, "utf8");
  writeFileSync(join(mind, ".gitignore"), "build\n", "utf8");
  writeFileSync(configFile, trackerConfig(resolvedTitle, resolvedNs), "utf8");
  // keep the empty general lane present on clone
  writeFileSync(join(issues, "00_general_issues", ".gitkeep"), "", "utf8");

  return { mind, title: resolvedTitle, namespace: resolvedNs };
}
